### ISSUE TITLE
ImportError: No module named serial.tools.list_ports

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy_install#14]
``` Python
import pypot.dynamixel

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4f7703136988> in <module>()
----> 1 import pypot.dynamixel

/home/poppy/dev/pypot/pypot/dynamixel/__init__.py in <module>()
      4 import logging
      5 
----> 6 import serial.tools.list_ports
      7 
      8 

ImportError: No module named serial.tools.list_ports
```

after a fresh install

**Comment by matthieu-lapeyre** [comment]
I did the installation again and it worked.

Maybe I have forgotten to reboot after the installation the first time.

Actually, if we connect to poppy some times after the installation is finished we do not have the information to reboot. 

Why not include the reboot directly in the installation script ?

**Comment by pierre-rouanet** [comment]
> Why not include the reboot directly in the installation script ?

From which reboot are you talking about? The first one or the second one? We could force the second reboot as well.

**Comment by matthieu-lapeyre** [comment]
the second one
