### ISSUE TITLE
Dev folder is empty

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy_install#16]
Python packages are now installed only with pip, but a LOT of humanoid and torso are not well assembled, the end user should be able to modify the configuration json file of the robot. 
If we create tag for each software version, we could simply clone the repo and checkout to the last stable version. What do you think @pierre-rouanet  ?

Otherwise, opencv-3.1.0  and puppet-master are installed in the '/home/poppy', but they should be in '/home/poppy/dev'

**Comment by matthieu-lapeyre** [comment]
+1
