### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy_install#21]
<img width="498" alt="capture d ecran 2016-05-01 a 22 14 30" src="https://cloud.githubusercontent.com/assets/4503773/14944099/25c4d856-0fea-11e6-96d7-33200433cf33.png">

After a fresh install

**Comment by show0k** [comment]
Are you sure it is a fresh install, or somewhere you install it again ?

**Comment by matthieu-lapeyre** [comment]
yep i'm sure.
From an Ubuntu 14.04.2
