### ISSUE TITLE
The poppy logo no more appears after ssh connexion

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy_install#22]
<img width="842" alt="capture d ecran 2016-05-01 a 22 19 13" src="https://cloud.githubusercontent.com/assets/4503773/14944128/d8fc654c-0fea-11e6-98f4-36ea396f6f00.png">

After a fresh installation ...

**Comment by show0k** [comment]
I think that it has never appears on this distribution, it should be fixed with [this commit](https://github.com/poppy-project/odroid-poppysetup/commit/f3134e9fe4cb20f2002aeaba67566dd713cfecfe#diff-16d8cc3fcaeb06088ec6e83d82cb4a8cR56).
