### ISSUE TITLE
Add scipy

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy_install#5]
Scipy is now required, it should be install as numpy with poppy_install.
Before installing scipy from pip you have to install the following packages (fortran dependencies)

```
sudo apt-get install libblas3gf libc6 libgcc1 libgfortran3 liblapack3gf libstdc++6 build-essential gfortran python-all-dev libatlas-base-dev
```

**Comment by pierre-rouanet** [comment]
PR please ^^

**Comment by pierre-rouanet** [comment]
Thanks @show0k !
