### ISSUE TITLE
@nicolas-rabault

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy_install#9]
@nicolas-rabault Comme il y a plusieurs curl avec des liens vers ton dépôt, l'ajout de scipy dans les dépendaces sur ce dépoôt n'a aucune influence... Tu pourrais faire un git pull depuis ton dépôt sur celui là pour prendre les commit ?

**Comment by nicolas-rabault** [comment]
Le mieux serait d'éliminer mon dépot sur mon compte...
Pour cela il faut rediriger tous les liens du script et le curl. après quoi j'updaterais mon dépot et je mettrais uniquemnt un readme qui redirige vers le poppy-install de poppy project.

**Comment by show0k** [comment]
Oui, mais pour l'instant poppy-install n'installe pas poppy-humanoid 
donc c'est peut être la solution la plus rapide pour ne pas avoir un 
installer cassé !
